[package]
edition = "2021"
name = "demo_toml_path"
publish = false
version = "0.4.0"

[package.metadata.syncdoc]
docs-path = "docs"

[dependencies]
syncdoc.workspace = true

[lints.rust]
missing_docs = "deny"
