[package]
edition = "2021"
name = "syncdoc_toml_path"
publish = false
version = "0.1.2"

[package.metadata.syncdoc]
docs-path = "docs"

[dependencies]
syncdoc.workspace = true

[lints.rust]
missing_docs = "deny"
